[project]
name = "flake8-datetime-import"
version = "0.1.0"
dependencies = [
    'importlib-metadata>=0.9; python_version<"3.8"',
]

[project.entry-points."flake8.extension"]
DTI = "flake8_datetime_import:Plugin"

[project.optional-dependencies]
dev = [
    "tox",
    "pre-commit",
]
gh = [
    "tox-gh"
]
build = [
    "build"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
profile = "black"
