---
name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py:
          - '3.10'
          - '3.7'
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - uses: actions/checkout@v2

      - name: Install
        run: pip install -e ".[dev,gh]"

      - name: Test
        run: tox
