---
name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py:
          - '3.11'
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
    steps:
      - uses: actions/checkout@v4

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install
        run: pip install -e ".[dev,gh]"

      - name: Test
        run: tox

      - name: Publish coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
