---
name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: py${{ matrix.py }} / flake8 ${{ matrix.flake8 }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - '3.14'
          - '3.13'
          - '3.12'
          - '3.11'
          - '3.10'
        flake8:
          - min
          - latest
        include:
          - flake8: min
            flake8-pin: 7.0.0
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.py }}

      - name: Sync
        run: uv sync

      - name: Pin flake8
        if: matrix.flake8-pin
        run: uv pip install 'flake8==${{ matrix.flake8-pin }}'

      - name: Test
        run: uv run --no-sync pytest --cov-report=xml

      - name: Publish coverage report
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
